# Generated by Django 2.1.3 on 2018-11-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrados',
            new_name='Registrado',
        ),
    ]
