# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: '3'
services:

  # PostgreSQL database.
  db-test:
    restart: always
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatypago_api-test
    env_file:
      - .env
    volumes:
      - db-test:/var/lib/postgresql/data # Using the declared volume.

  # RabbitMQ.
  rabbit:
    volumes:
      - broker-test:/var/lib/rabbitmq # Using the declared volume.
    env_file:
      - .env

  # Django web server.
  app:
    image: chatypago_api-app-test
    environment: &environment
      - STAGE=test
      - DJANGO_SETTINGS_MODULE=config.settings.test
      - DJANGO_DB_URL=postgis://postgres:postgres@db-test:5432/chatypago_api-test
      - DJANGO_SECRET_KEY=j36%5df7q5+ov)wz+(=vt7d81ka^xx!5%0)nx=z2i&)*5r^
      - DJANGO_REDIS_CACHE_URL=redis://redis:6379/2
      - DJANGO_REDIS_SESSION_URL=redis://redis:6379/3
      - DJANGO_AWS_STORAGE_BUCKET_NAME=bucket_name
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
      args:
        stage: test
    volumes:
      - .:/usr/src
    env_file:
      - .env
    depends_on:
      - db-test
      - redis

volumes:
  db-test:
  broker-test:
